# Generated by Django 5.0.7 on 2024-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_advice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterVictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_phone', models.CharField(max_length=20)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_type', models.CharField(choices=[('AIRTIME', 'Airtime'), ('MONEY', 'Mobile Money')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
